/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customerPackage;

/**
 *
 * @author PC
 */
import menuItems.Menu;
import starting.HomepageForm;

public class CustomerWelcomeForm extends javax.swing.JFrame
{

    Customer customer;
    String orderinString;

    /**
     * Creates new form CustomerFormm
     */
    public CustomerWelcomeForm()
    {
        initComponents();
    }

    public CustomerWelcomeForm(Customer c, String s)
    {
        initComponents();
        this.setLocationRelativeTo(null); //center form in screen
        customer = c;
        System.out.println(c.getId());
        orderinString = s;
        String[] name = c.getName().split(" ");
        lblWelcome.setText("Welcome " + name[0] + ",");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcomeCust = new javax.swing.JPanel();
        lblmessage = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        pHeader2 = new javax.swing.JPanel();
        btnLogout2 = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        btnOrdersCustomer = new javax.swing.JButton();
        btnMakeOrderCustomer = new javax.swing.JButton();
        btnMenuCustomer = new javax.swing.JButton();
        btnBestSellersCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1217, 871));
        setUndecorated(true);
        getContentPane().setLayout(null);

        pnlWelcomeCust.setLayout(null);

        lblmessage.setFont(new java.awt.Font("Rockwell Condensed", 1, 50)); // NOI18N
        lblmessage.setForeground(new java.awt.Color(255, 255, 255));
        lblmessage.setText("What would you like to eat today?");
        lblmessage.setName(""); // NOI18N
        pnlWelcomeCust.add(lblmessage);
        lblmessage.setBounds(210, 110, 720, 90);

        lblWelcome.setFont(new java.awt.Font("Rockwell Condensed", 1, 50)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome");
        lblWelcome.setName(""); // NOI18N
        pnlWelcomeCust.add(lblWelcome);
        lblWelcome.setBounds(330, 20, 480, 90);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managerPackage/Welcome bg.jpg"))); // NOI18N
        pnlWelcomeCust.add(lblImage);
        lblImage.setBounds(0, -20, 1220, 830);

        getContentPane().add(pnlWelcomeCust);
        pnlWelcomeCust.setBounds(0, 70, 1220, 810);

        pHeader2.setBackground(new java.awt.Color(255, 213, 0));
        pHeader2.setName("pHeader"); // NOI18N
        pHeader2.setPreferredSize(new java.awt.Dimension(1062, 70));
        pHeader2.setLayout(null);

        btnLogout2.setBackground(new java.awt.Color(255, 213, 0));
        btnLogout2.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnLogout2.setForeground(new java.awt.Color(127, 72, 101));
        btnLogout2.setText("Log out");
        btnLogout2.setToolTipText("");
        btnLogout2.setBorder(null);
        btnLogout2.setBorderPainted(false);
        btnLogout2.setContentAreaFilled(false);
        btnLogout2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout2.setName(""); // NOI18N
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });
        pHeader2.add(btnLogout2);
        btnLogout2.setBounds(1080, 19, 101, 40);

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setFont(new java.awt.Font("Rockwell Condensed", 0, 52)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(127, 72, 101));
        lbLogo.setText("GUSTO");
        lbLogo.setToolTipText("");
        pHeader2.add(lbLogo);
        lbLogo.setBounds(30, 10, 120, 62);

        btnOrdersCustomer.setBackground(new java.awt.Color(255, 213, 0));
        btnOrdersCustomer.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnOrdersCustomer.setForeground(new java.awt.Color(127, 72, 101));
        btnOrdersCustomer.setText("My Orders");
        btnOrdersCustomer.setBorder(null);
        btnOrdersCustomer.setBorderPainted(false);
        btnOrdersCustomer.setContentAreaFilled(false);
        btnOrdersCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdersCustomer.setPreferredSize(new java.awt.Dimension(87, 29));
        btnOrdersCustomer.setRequestFocusEnabled(false);
        btnOrdersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersCustomerActionPerformed(evt);
            }
        });
        pHeader2.add(btnOrdersCustomer);
        btnOrdersCustomer.setBounds(901, 26, 184, 29);

        btnMakeOrderCustomer.setBackground(new java.awt.Color(255, 213, 0));
        btnMakeOrderCustomer.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnMakeOrderCustomer.setForeground(new java.awt.Color(127, 72, 101));
        btnMakeOrderCustomer.setText("Make Order");
        btnMakeOrderCustomer.setBorder(null);
        btnMakeOrderCustomer.setBorderPainted(false);
        btnMakeOrderCustomer.setContentAreaFilled(false);
        btnMakeOrderCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMakeOrderCustomer.setPreferredSize(new java.awt.Dimension(87, 29));
        btnMakeOrderCustomer.setRequestFocusEnabled(false);
        btnMakeOrderCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeOrderCustomerActionPerformed(evt);
            }
        });
        pHeader2.add(btnMakeOrderCustomer);
        btnMakeOrderCustomer.setBounds(750, 20, 170, 40);

        btnMenuCustomer.setBackground(new java.awt.Color(255, 213, 0));
        btnMenuCustomer.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnMenuCustomer.setForeground(new java.awt.Color(127, 72, 101));
        btnMenuCustomer.setText("Main Menu");
        btnMenuCustomer.setBorder(null);
        btnMenuCustomer.setBorderPainted(false);
        btnMenuCustomer.setContentAreaFilled(false);
        btnMenuCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuCustomer.setPreferredSize(new java.awt.Dimension(87, 29));
        btnMenuCustomer.setRequestFocusEnabled(false);
        btnMenuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCustomerActionPerformed(evt);
            }
        });
        pHeader2.add(btnMenuCustomer);
        btnMenuCustomer.setBounds(430, 20, 153, 40);

        btnBestSellersCustomer.setBackground(new java.awt.Color(255, 213, 0));
        btnBestSellersCustomer.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnBestSellersCustomer.setForeground(new java.awt.Color(127, 72, 101));
        btnBestSellersCustomer.setText("Best Selling");
        btnBestSellersCustomer.setBorder(null);
        btnBestSellersCustomer.setBorderPainted(false);
        btnBestSellersCustomer.setContentAreaFilled(false);
        btnBestSellersCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBestSellersCustomer.setPreferredSize(new java.awt.Dimension(87, 29));
        btnBestSellersCustomer.setRequestFocusEnabled(false);
        btnBestSellersCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestSellersCustomerActionPerformed(evt);
            }
        });
        pHeader2.add(btnBestSellersCustomer);
        btnBestSellersCustomer.setBounds(590, 20, 153, 40);

        getContentPane().add(pHeader2);
        pHeader2.setBounds(0, 0, 1220, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        HomepageForm homepage = new HomepageForm();
        homepage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void btnOrdersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersCustomerActionPerformed
        ShowOrders s = new ShowOrders(customer, orderinString);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrdersCustomerActionPerformed

    private void btnMakeOrderCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeOrderCustomerActionPerformed
        // TODO add your handling code here:
        OrderForm o = new OrderForm(customer, orderinString);
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMakeOrderCustomerActionPerformed

    private void btnMenuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCustomerActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_btnMenuCustomerActionPerformed

    private void btnBestSellersCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestSellersCustomerActionPerformed
        BestSellerForm b= new BestSellerForm(customer, orderinString);
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBestSellersCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(CustomerWelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(CustomerWelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(CustomerWelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(CustomerWelcomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CustomerWelcomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBestSellersCustomer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnMakeOrderCustomer;
    private javax.swing.JButton btnMenuCustomer;
    private javax.swing.JButton btnOrdersCustomer;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblmessage;
    private javax.swing.JPanel pHeader;
    public static javax.swing.JPanel pHeader2;
    private javax.swing.JPanel pnlWelcomeCust;
    // End of variables declaration//GEN-END:variables
}
